//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiretoriaEscolar.Infra.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alunos
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string CPF { get; set; }
        public string Telefone { get; set; }
        public int TurmaId { get; set; }
        public System.DateTime DataNascimento { get; set; }
    
        public virtual Turmas Turma { get; set; }
        public virtual Enderecos EnderecoAluno { get; set; }
    }
}
