//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiretoriaEscolar.Infra.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Escolas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Escolas()
        {
            this.Turma = new HashSet<Turmas>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public string CNPJ { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Turmas> Turma { get; set; }
        public virtual Enderecos Endereco { get; set; }
    }
}
