//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiretoriaEscolar.Infra.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Turmas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Turmas()
        {
            this.Aluno = new HashSet<Alunos>();
        }
    
        public int Id { get; set; }
        public string Ano { get; set; }
        public string Serie { get; set; }
        public string Classe { get; set; }
        public int EscolaId { get; set; }
    
        public virtual Escolas Escola { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alunos> Aluno { get; set; }
    }
}
